import json
import re
import logging
import math
from sqlalchemy.orm import Session
from config import settings
from intent_engine import IntentEngine
from agent_builder.models import (
    BuilderSandboxSession, BuilderSandboxMessage,
    BuilderKnowledge, BuilderKnowledgeChunk
)
from embedding_service import EmbeddingService

logger = logging.getLogger(__name__)

def get_custom_rag_context(db: Session, agent_id: str, query: str) -> str:
    """
    Search database for knowledge chunks corresponding to agent_id,
    calculate cosine similarity against query embedding, and return formatted context.
    """
    try:
        chunks = db.query(BuilderKnowledgeChunk).join(
            BuilderKnowledge, BuilderKnowledge.knowledge_id == BuilderKnowledgeChunk.knowledge_id
        ).filter(BuilderKnowledge.agent_id == agent_id).all()

        if not chunks:
            return ""

        query_vector = EmbeddingService.embed(query)
        if not query_vector:
            return ""

        scored_chunks = []
        for c in chunks:
            if not c.embedding:
                continue
            dot = sum(a * b for a, b in zip(query_vector, c.embedding))
            norm_a = math.sqrt(sum(a * a for a in query_vector))
            norm_b = math.sqrt(sum(b * b for b in c.embedding))
            if norm_a == 0 or norm_b == 0:
                sim = 0.0
            else:
                sim = dot / (norm_a * norm_b)
            if sim > 0.35:
                scored_chunks.append((sim, c.content))

        scored_chunks.sort(key=lambda x: x[0], reverse=True)
        top_chunks = scored_chunks[:3]

        if not top_chunks:
            return ""

        context_lines = []
        for idx, (sim, text) in enumerate(top_chunks):
            context_lines.append(f"【自定义商品库/话术匹配段 {idx+1}】 (匹配度 {sim:.2f}):\n{text}")
        return "\n\n".join(context_lines)
    except Exception as e:
        logger.error(f"Failed to calculate custom RAG context: {e}")
        return ""

# Standard B2B product stock for reference
PRODUCT_CATALOG = """
- iPhone 8: 售价 180 万印尼盾 (成色良好，预算极低推荐)
- iPhone XR: 售价 300 万印尼盾 (热销爆款，成色95新)
- iPhone 11: 售价 420 万印尼盾 (成色良好，拍照出色)
- iPhone 11 Pro: 售价 550 万印尼盾 (旗舰配置，重度拍照与游戏推荐)
- iPhone 13 Pro: 售价 850 万印尼盾 (顶奢性能，超高预算推荐)
"""

def extract_slots_from_message(content: str) -> dict:
    """
    Use LLM1 to extract slot variables and planned intent from the current customer message.
    """
    prompt = f"""
你是一个专用的B2B销售意图与规划器。请分析下面的客户说话内容，提取出关于其购机偏好、分期资质以及检索规划。
只允许输出合法的 JSON 对象，不要包含 markdown 代码块、解释或额外字符。

变量列表及说明：
1. budget: 用户提及的购机预算范围（如 2500-3000, 300万等），没有提及则输出 null。
2. phone_usage: 用户购机的主要用途（如 玩游戏, 拍照, 日常社交, 办公 等），没有提及则输出 null。
3. battery_health: 用户对电池健康度的要求（如 85%+, 90%+ 等），没有则输出 null。
4. age: 用户提及的年龄（数字或文字，如 18, 25 等），没有则输出 null。
5. job: 用户提及的工作性质，可选值：'固定工作', '无固定工作', '在校学生', '失业/无业', null。注意：必须严格区分“有工作”与“固定工作”。除非客户明确说出是“固定工作”（或稳定工作、正式工作），否则工作性质（job）必须输出 null，绝对不能直接判定为“固定工作”。
6. ktp: 用户是否持有印尼 KTP 身份证，可选值：'持有', '无', null。
7. ask_installment: 用户是否提及、询问分期付款或贷款方案，可选值：true (提到), false (没提到)。
8. planned_intent: 规划的目标意图主题，可选值: 'pricing' (价格/收费), 'product_recommendation' (推荐机型), 'installment_rules' (分期资格/规则), 'faq' (其他咨询), 'greeting' (问候语), 'other'。
9. requires_knowledge_lookup: 是否需要检索自定义商品库/知识库以回答此问题，可选值: true, false。

输入：
"{content}"

JSON 输出格式样例：
{{
  "budget": "300万",
  "phone_usage": "玩游戏",
  "battery_health": null,
  "age": null,
  "job": null,
  "ktp": null,
  "ask_installment": false,
  "planned_intent": "product_recommendation",
  "requires_knowledge_lookup": true
}}
"""
    try:
        res = IntentEngine.run_llm1_json_prompt(prompt, user_id="sandbox_extractor")
        if isinstance(res, dict):
            return res
    except Exception as e:
        logger.error(f"Slot extraction failed: {e}")

    # Fallback to simple regex if LLM fails or is timeout
    fallback = {
        "budget": None,
        "phone_usage": None,
        "battery_health": None,
        "age": None,
        "job": None,
        "ktp": None,
        "ask_installment": False,
        "planned_intent": "other",
        "requires_knowledge_lookup": True
    }
    content_lower = content.lower()
    if "分期" in content_lower or "贷款" in content_lower or "installment" in content_lower or "credit" in content_lower:
        fallback["ask_installment"] = True
        fallback["planned_intent"] = "installment_rules"
    # Match basic numbers for budget
    budget_match = re.search(r"(\d+万|\d+元|\d+[-~]\d+)", content)
    if budget_match:
        fallback["budget"] = budget_match.group(1)
        fallback["planned_intent"] = "product_recommendation"
    return fallback

def run_sandbox_agentic_flow(db: Session, session: BuilderSandboxSession, user_content: str) -> tuple[str, dict]:
    """
    Run the state-machine and slot-extraction logic.
    Returns:
        reply_text (str): The response generated by the AI.
        trace (dict): Execution details (current node, slots filled, rules triggered, reasoning).
    """
    # 1. Extraction Phase
    extracted = extract_slots_from_message(user_content)

    # Load current session state
    vars_dict = session.variables or {}

    # Update active slots
    new_slots = {}
    for key in ["budget", "phone_usage", "battery_health", "age", "job", "ktp"]:
        val = extracted.get(key)
        if val is not None and val != "null" and val != "":
            vars_dict[key] = str(val)
            new_slots[key] = str(val)

    # Check if installment inquiry is triggered
    if extracted.get("ask_installment") or "分期" in user_content or "贷款" in user_content:
        vars_dict["installment_triggered"] = True

    current_node = vars_dict.get("current_node", "需求探询与推荐")
    action_triggered = "常规咨询响应"
    reasoning = "继续收集客户购机需求以匹配合适机型。"

    # 2. SOP State Transition Logic
    # Rules:
    # A. If installment asked -> Transition to "分期方案介绍"
    if vars_dict.get("installment_triggered") and current_node == "需求探询与推荐":
        current_node = "分期方案介绍"
        action_triggered = "激活「分期方案介绍」技能"
        reasoning = "监测到客户询问分期付款，激活该技能并根据约束进行解答。"

    # B. If in "分期方案介绍", check qualifications. If any missing -> transition to "高意向转化与资格确认"
    if current_node == "分期方案介绍":
        missing_quals = []
        if vars_dict.get("age") == "未收集": missing_quals.append("年龄")
        if vars_dict.get("job") == "未收集": missing_quals.append("工作")
        if vars_dict.get("ktp") == "未收集": missing_quals.append("KTP")

        if missing_quals:
            current_node = "高意向转化与资格确认"
            action_triggered = "询问资质三要素"
            reasoning = f"客户表达分期意向，但缺失 {', '.join(missing_quals)} 资质参数，启动资格审核流程。"

    # C. In "高意向转化与资格确认", check if fully qualified or disqualified
    if current_node == "高意向转化与资格确认":
        age_str = vars_dict.get("age")
        job_str = vars_dict.get("job")
        ktp_str = vars_dict.get("ktp")
        details_verified = vars_dict.get("details_verified", "未核实")

        # Disqualification checks
        is_disqualified = False
        disqualify_reason = ""

        # Parse age
        if age_str != "未收集":
            try:
                age_num = int(re.search(r"\d+", age_str).group())
                if age_num < 21:
                    is_disqualified = True
                    disqualify_reason = "年龄未满 21 岁"
            except Exception:
                if "学生" in age_str or "18" in age_str or "小于" in age_str:
                    is_disqualified = True
                    disqualify_reason = "年龄不足或为在校学生"

        # Check job
        if job_str != "未收集" and job_str in ["无固定工作", "失业/无业", "学生无固定工作", "无"]:
            is_disqualified = True
            disqualify_reason = "没有固定工作"

        # Check KTP
        if ktp_str != "未收集" and ktp_str in ["无", "没有"]:
            is_disqualified = True
            disqualify_reason = "没有持有印尼本地 KTP 身份证"

        if is_disqualified:
            action_triggered = "拒绝分期申请并引导全款"
            reasoning = f"识别到用户 {disqualify_reason}，不满足贷款三要素，触发规则约束：拒绝办理并推荐全款或其他低预算机型。"
        elif age_str != "未收集" and job_str != "未收集" and ktp_str != "未收集":
            if details_verified == "未核实":
                action_triggered = "核实资质细节与提醒证明材料"
                reasoning = "已收集到资质三要素，进入实质性审查阶段：追问客户具体固定工作名称，并提醒准备KTP和收入证明/工资流水。"
                vars_dict["details_verified"] = "已核实"
            else:
                # Fully qualified
                action_triggered = "符合资格 -> 触发转人工"
                reasoning = "贷款资格三要素（年龄满21岁 + 固定工作 + 持有印尼KTP）核对均合格，且已完成实质性工作性质审查并提醒证明文件，自动总结并转交客户经理预定。"
                session.status = "completed"

    # Save state back to session
    vars_dict["current_node"] = current_node
    session.variables = vars_dict

    # 3. Text Generation Phase using LLM2
    # Retrieve dialog history
    history = db.query(BuilderSandboxMessage).filter(BuilderSandboxMessage.session_id == session.session_id).order_by(BuilderSandboxMessage.created_at.asc()).all()
    history_text = ""
    for msg in history:
        role_label = "客户" if msg.sender == "customer" else "AI客服"
        history_text += f"{role_label}: {msg.content}\n"

    # Query Custom Knowledge if planned
    requires_lookup = extracted.get("requires_knowledge_lookup", True)
    if requires_lookup is False or str(requires_lookup).lower() == "false":
        custom_context = ""
    else:
        custom_context = get_custom_rag_context(db, session.agent_id, user_content)

    catalog_context = PRODUCT_CATALOG
    if custom_context:
        catalog_context = f"=== 商家自定义库存与规则库 ===\n{custom_context}\n\n=== 默认基础商品库 ===\n{PRODUCT_CATALOG}"

    generation_prompt = f"""
你是一个专门扮演印尼二手iPhone手机销售助手 Spark 的 AI 客服，当前服务模式是 B2B 零售会话。
请根据当前【业务节点规则】、【对话历史记录】、【槽位变量状态】以及【标准库存价格表】，生成销售话术。

标准库存价格表 (只允许在此范围内推荐)：
{catalog_context}

业务节点规则与约束：
【警告：高风险红线约束】
1. 绝对严禁主动向客户推销、提及、提议“分期”、“分期付款”、“贷款”、“credit”或“installment”方案。只要变量 分期已被触发 (installment_triggered) 为 False，哪怕客户因为价格太贵而反复纠缠、砍价、哀求，或者表示预算不够，你也绝对不能主动介绍或询问其分期资格（包括绝对不能主动询问“满21岁了吗”、“有固定工作吗”、“有KTP吗”这三要素）。如果客户询问付款方式，只告知支持全款转账（银行转账/电子钱包），绝对不能主动说我们可以分期。违背此项将直接导致审核失败！
2. 如果触发了分期咨询（即“分期已被触发”为 True），首先说明首付比例最少10%，然后必须委婉询问客户是否满足三要素（是否满21岁、是否有固定工作、是否持有印尼KTP）。
3. 如果 决策执行状态 为“核实资质细节与提醒证明材料”，你必须委婉询问客户具体从事的固定工作性质或职业名称，并善意提醒客户转人工前需准备好印尼KTP和工资流水等证明文件。绝对不能在此轮直接说恭喜合格和转人工！
4. 如果 决策执行状态 为“符合资格 -> 触发转人工”，你必须热烈恭喜客户已符合分期资质，说明已为其登记意向，并立即告知转接人工客服经理。
5. 绝不随意报出利息或月供数字，除非掌握了客户的具体分期方案依据。如果客户未确定意向机型或购机预算，且多次追问分期费率，必须温柔而坚定地拒绝给出具体数字，并告知必须先确定意向机型和预算后，金融机构才能给出具体报价；然后顺势追问其对手机的用途 and 预算偏好。绝对不能报出任何具体手机型号（如 iPhone XR）的月供或首付作为例子。
6. 如果客户不满足分期资格，告诉其无法办理分期，并推荐全款机型（比如预算低就推荐 iPhone 8 全款 180万）。

当前槽位变量状态与决策状态：
- 购机预算：{vars_dict.get('budget')}
- 主要用途：{vars_dict.get('phone_usage')}
- 电池健康度：{vars_dict.get('battery_health')}
- 年龄：{vars_dict.get('age')}
- 工作：{vars_dict.get('job')}
- 身份证KTP：{vars_dict.get('ktp')}
- 分期已被触发：{vars_dict.get('installment_triggered')}
- 资质细节已核实：{vars_dict.get('details_verified')}
- 当前处于SOP节点：{current_node}
- 决策执行状态：{action_triggered}
- 决策原因：{reasoning}

最近对话历史：
{history_text}
客户刚发出的消息: "{user_content}"

任务要求：
1. 你的回答必须口语化，像微信销售，亲切、自然、简洁。不要官腔官调，中文表达，根据语境可以穿插极少印尼语单词（如 KTP, Rupiah）。
2. 只输出最终的销售回复，不要包含任何旁白、解释或思考过程。
"""

    # Call Generator LLM (Usually LLM2 is for generation)
    reply_text = ""
    try:
        # Construct openai request spec
        url = settings.LLM2_API_URL.rstrip('/') + "/chat/completions"
        headers = {
            "Authorization": f"Bearer {settings.LLM2_API_KEY}",
            "Content-Type": "application/json"
        }
        payload = {
            "model": settings.LLM2_MODEL,
            "messages": [{"role": "user", "content": generation_prompt}],
            "temperature": 0.3
        }
        res = IntentEngine._post_json(url, headers, payload, timeout=settings.LLM2_TIMEOUT_SECONDS)
        if res.status_code == 200:
            res_data = res.json()
            reply_text = res_data["choices"][0]["message"]["content"].strip()
    except Exception as e:
        logger.error(f"Sandbox reply generation failed: {e}")

    # Standard Rule-based Fallback replies if LLM fails
    if not reply_text:
        if action_triggered == "符合资格 -> 触发转人工":
            reply_text = "太好了！您的资质完全符合条件。我已将您的意向机型和分期方案记录好，这就为您转接专属客户经理，帮您办理预定和后续签约手续，请稍等哦！"
        elif action_triggered == "拒绝分期申请并引导全款":
            reply_text = "抱歉亲，根据印尼本地金融机构的评估规则，办理分期需要年满21岁、有固定工作并持有KTP身份证。您这边可能暂时无法办理分期。不过如果您预算在200万左右，我们有一批高性价比的 iPhone 8 支持全款购买，也是非常划算的，您看需要了解一下吗？"
        elif current_node == "高意向转化与资格确认":
            reply_text = "想要了解分期的话，我们需要先做个快速审核。请问您是否年满21周岁、在印尼当地有固定工作，并且持有KTP身份证呢？"
        elif current_node == "分期方案介绍":
            reply_text = "好的亲！我们这边的iPhone支持分期贷款购买，首付最少只要10%起，期数支持 3/6/12 期。为了帮您核算资格，请问您目前是否有固定工作、年满21岁，并且持有印尼KTP身份证呢？"
        else:
            reply_text = "您好！我是 SPARK 手机零售助手。我们有成色非常棒的二手 iPhone 支持全款或分期购买。请问您目前的购机预算大概是多少呢？"

    # 4. Reflective / Self-Correction Phase
    reflection_triggered = False
    reflection_reason = ""

    # Rule A: Enforce installment mention blockage when installment is not triggered
    if not vars_dict.get("installment_triggered"):
        for term in ["分期", "贷款", "credit", "installment"]:
            if term in reply_text:
                logger.warning(f"Reflection: reply_text proactively mentioned installment term '{term}' but installment_triggered is False. Correcting.")
                reply_text = "您好！我们有非常高性价比的二手 iPhone，支持银行卡转账或电子钱包全款支付，目前购买部分机型有配件赠品。请问您目前的购机预算大概是多少呢？"
                reflection_triggered = True
                reflection_reason = "检测到 AI 主动提及分期，已被物理拦截拦截并重置为全款引导话术。"
                break

    # Rule B: Verify pricing matches standard catalog bounds (e.g. iPhone XR is 300万)
    xr_match = re.search(r"(xr|iphone\s*xr).*?(\d+)\s*万", reply_text, flags=re.IGNORECASE)
    if xr_match:
        price_val = int(xr_match.group(2))
        if price_val != 300:
            logger.warning(f"Reflection: Pricing mismatch for iPhone XR. AI generated {price_val}万, expected 300万. Correcting.")
            reply_text = re.sub(r"(xr|iphone\s*xr).*?\d+\s*万", r"\1 售价 300 万", reply_text, flags=re.IGNORECASE)
            reflection_triggered = True
            reflection_reason = f"检测到价格幻觉（iPhone XR {price_val}万），自动校准价格为 300 万印尼盾。"

    # Post-process trace details
    trace = {
        "current_node": current_node,
        "slots_filled": new_slots if new_slots else "无新槽位提取",
        "action_triggered": action_triggered,
        "reason": reasoning
    }
    if reflection_triggered:
        trace["reflection_triggered"] = True
        trace["reflection_reason"] = reflection_reason
        trace["planned_intent"] = extracted.get("planned_intent", "other")

    return reply_text, trace
